version: "3.9"

services:
  zero2prod:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - zero2prod
    ports:
      - "8888:8888"
  postgres:
    image: postgres:16.1-alpine
    restart: unless-stopped
    networks:
      - zero2prod
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - DEBUG=false
      - POSTGRES_DB=newsletter
    volumes:
      - ./local-data:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

networks:
  zero2prod:
