# Prometheus configuration for Milvus
# Requires prometheus 2.X
# Run with:
# $ prometheus -config.file = prometheus.yml
# my global config
global:
  scrape_interval: 5s # Set the scrape interval every 2 seconds. The default is every 1 minute.
  evaluation_interval: 30s # Evaluate rules every 2 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any time series scraped from this config.
  - job_name: "zero2prod"
    static_configs:
      - targets: ["localhost:8888"]
    metrics_path: "/metrics"
